"""Map exported INT8 weights into banked FPGA .mem files.

The default mapping targets snn_top.v:
- bank = neuron_id[0]
- addr = neuron_id[6:1]

For 2-bank, 64-depth memory this gives capacity for 128 neuron entries.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Tuple

import numpy as np


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Map INT8 SNN weights to banked .mem files for FPGA.")
    p.add_argument(
        "--weights-npz",
        type=Path,
        default=None,
        help="Path to weights_int8.npz. If omitted, uses --export-dir/weights_int8.npz",
    )
    p.add_argument(
        "--export-dir",
        type=Path,
        default=Path("./artifacts/export_int8"),
        help="Directory containing weights_int8.npz generated by export_weights.py",
    )
    p.add_argument(
        "--layer",
        type=str,
        default="fc1",
        help="Layer name prefix to map (e.g., fc1, fc2, fc3).",
    )
    p.add_argument(
        "--vector-policy",
        type=str,
        default="row_mean",
        choices=["first_col", "row_mean", "row_maxabs"],
        help="How to collapse each output-neuron weight row into one INT8 value.",
    )
    p.add_argument("--num-banks", type=int, default=2)
    p.add_argument("--bank-depth", type=int, default=64)
    p.add_argument(
        "--out-dir",
        type=Path,
        default=Path("./artifacts/fpga_mem"),
        help="Output directory for bank .mem files and metadata.",
    )
    return p.parse_args()


def _layer_key(npz_keys: Tuple[str, ...], layer: str) -> str:
    expected = f"{layer}_weight_int8"
    if expected in npz_keys:
        return expected
    raise KeyError(
        f"Layer key `{expected}` not found in NPZ. Available keys: {list(npz_keys)}"
    )


def _collapse_weights(w: np.ndarray, policy: str) -> np.ndarray:
    if w.ndim == 1:
        return w.astype(np.int16)
    if w.ndim != 2:
        raise ValueError(f"Expected 1D/2D layer weights, got shape {w.shape}.")

    if policy == "first_col":
        vec = w[:, 0].astype(np.int16)
    elif policy == "row_mean":
        vec = np.rint(w.astype(np.float32).mean(axis=1)).astype(np.int16)
    elif policy == "row_maxabs":
        idx = np.abs(w).argmax(axis=1)
        vec = w[np.arange(w.shape[0]), idx].astype(np.int16)
    else:
        raise ValueError(f"Unsupported policy: {policy}")

    return np.clip(vec, -128, 127).astype(np.int16)


def _twos_complement_hex_i8(v: int) -> str:
    return f"{np.uint8(np.int8(v)):02x}"


def map_to_banks(
    neuron_vals: np.ndarray,
    num_banks: int,
    bank_depth: int,
) -> Tuple[np.ndarray, int]:
    total_capacity = num_banks * bank_depth
    mem_vec = np.zeros(total_capacity, dtype=np.int8)

    used = min(total_capacity, neuron_vals.shape[0])
    mem_vec[:used] = np.clip(neuron_vals[:used], -128, 127).astype(np.int8)

    banks = np.zeros((num_banks, bank_depth), dtype=np.int8)
    for neuron_id in range(total_capacity):
        bank = neuron_id % num_banks
        addr = neuron_id // num_banks
        banks[bank, addr] = mem_vec[neuron_id]
    return banks, used


def main() -> None:
    args = parse_args()

    npz_path = args.weights_npz if args.weights_npz is not None else (args.export_dir / "weights_int8.npz")
    if not npz_path.exists():
        raise FileNotFoundError(f"Could not find NPZ file: {npz_path}")

    args.out_dir.mkdir(parents=True, exist_ok=True)

    npz = np.load(npz_path)
    key = _layer_key(tuple(npz.keys()), args.layer)
    weight = npz[key].astype(np.int8)

    neuron_vals = _collapse_weights(weight, args.vector_policy)
    banks, used = map_to_banks(neuron_vals, args.num_banks, args.bank_depth)

    for b in range(args.num_banks):
        mem_path = args.out_dir / f"bank{b}.mem"
        with mem_path.open("w", encoding="utf-8") as f:
            for v in banks[b]:
                f.write(_twos_complement_hex_i8(int(v)) + "\n")

    combined_path = args.out_dir / "combined_neuron_weights.mem"
    with combined_path.open("w", encoding="utf-8") as f:
        for neuron_id in range(args.num_banks * args.bank_depth):
            bank = neuron_id % args.num_banks
            addr = neuron_id // args.num_banks
            val = int(banks[bank, addr])
            f.write(f"{neuron_id:03d} {bank} {addr:03d} {_twos_complement_hex_i8(val)} {val}\n")

    meta: Dict[str, object] = {
        "weights_npz": str(npz_path.resolve()),
        "layer_key": key,
        "original_shape": list(weight.shape),
        "vector_policy": args.vector_policy,
        "num_banks": args.num_banks,
        "bank_depth": args.bank_depth,
        "mapped_entries": int(used),
        "total_capacity": int(args.num_banks * args.bank_depth),
        "note": (
            "Mapped neuron_id to bank/address as bank=neuron_id%num_banks, "
            "addr=neuron_id//num_banks."
        ),
    }
    with (args.out_dir / "mapping_meta.json").open("w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)

    print("Weight-bank mapping complete.")
    print(f"Source NPZ: {npz_path.resolve()}")
    print(f"Layer key: {key}, original shape: {weight.shape}")
    print(f"Entries mapped: {used}/{args.num_banks * args.bank_depth}")
    print(f"Output directory: {args.out_dir.resolve()}")


if __name__ == "__main__":
    main()
